# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "151a7w2gqrv1svabhzmalrjr2pdbb9ys8zhrfz02779rjhzfz916";
    sha256bin64 = "1957q2wdkymibxqzpcq71fj3q6gca888r7gr621z0c03p0izlb7z";
    version = "60.0.3112.24";
  };
  dev = {
    sha256 = "15642f0nalx3zqdlr5ldcbrpxnadav3z6sl3imvzj2ssv3nbh25m";
    sha256bin64 = "0lbma509m3ppy3hg34r10ijhw3m92qxm147qhw0k4lpwdcmm6fnm";
    version = "60.0.3112.20";
  };
  stable = {
    sha256 = "1naqlxz9w07nlnwxkmxwf9jnxvmagj88xcjqh9r873a26wsypyl3";
    sha256bin64 = "1h086irdsjs27n7ch54hy7zbiypc4swr8wnxjha1q39wc1bpc7hl";
    version = "59.0.3071.109";
  };
}
